name: Tests

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          mkdir -p ~/.local/share/neogit-test/site/pack/plenary.nvim/start
          cd ~/.local/share/neogit-test/site/pack/plenary.nvim/start
          git clone https://github.com/nvim-lua/plenary.nvim

          mkdir -p ~/.local/share/neogit-test/site/pack/telescope.nvim/start
          cd ~/.local/share/neogit-test/site/pack/telescope.nvim/start
          git clone https://github.com/nvim-telescope/telescope.nvim

      - name: Install Neovim
        run: |
          wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
          tar -zxf nvim-linux64.tar.gz
          sudo ln -s $(pwd)/nvim-linux64/bin/nvim /usr/local/bin

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Luassert Test
        continue-on-error: true
        env:
          ci: "1"
        run: |
          make test

      - name: E2E Test
        env:
          ci: "1"
        run: |
          bundle exec rspec
