name: Tests

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Test
    runs-on: macos-latest
    env:
      CI: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        run: |
          wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
          tar -zxf nvim-linux64.tar.gz
          chmod +x $(pwd)/nvim-linux64/bin/nvim
          sudo ln -s $(pwd)/nvim-linux64/bin/nvim /usr/local/bin

      - name: Install Dependencies
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/
          cd ~/.local/share/nvim/site/pack/

          mkdir -p ./plenary.nvim/start
          cd ./plenary.nvim/start
          git clone https://github.com/nvim-lua/plenary.nvim

          mkdir -p ./telescope.nvim/start
          cd ./telescope.nvim/start
          git clone https://github.com/nvim-telescope/telescope.nvim

      # - name: Luassert Test
      #   continue-on-error: true
      #   run: |
      #     make test

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: E2E Test
        env:
          NVIM_RUBY_LOG_LEVEL: "debug"
        run: |
          bundle exec rspec
